version: '2'
services:
  zookeeper:
    image: zookeeper
  kbroker0:
    image: rbi13/kafka
    links:
       - zookeeper
    command: >
      /bin/bash bin/kafka-server-start.sh config/server.properties
      --override zookeeper.connect=zookeeper:2181
      --override broker.id=0
      --override listeners=PLAINTEXT://:9093
  kbroker1:
    image: rbi13/kafka
    links:
       - zookeeper
    command: >
      /bin/bash bin/kafka-server-start.sh config/server.properties
      --override zookeeper.connect=zookeeper:2181
      --override broker.id=1
      --override listeners=PLAINTEXT://:9094
  kbroker2:
    image: rbi13/kafka
    links:
       - zookeeper
    command: >
      /bin/bash bin/kafka-server-start.sh config/server.properties
      --override zookeeper.connect=zookeeper:2181
      --override broker.id=2
      --override listeners=PLAINTEXT://:9095
